version: '3.4'

services:
  webrazorpages:
    image: ${DOCKER_REGISTRY-}webshop/razorpages
    build:
      context: .
      dockerfile: src/WebRazorPages/Dockerfile

  web:
    image: ${DOCKER_REGISTRY-}webshop/web
    build:
      context: .
      dockerfile: src/Web/Dockerfile

